# Generated by Django 5.2.4 on 2025-09-16 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100, verbose_name='المسمى الوظيفي')),
                ('previous_school_name', models.CharField(max_length=100, verbose_name='اسم المدرسة السابقة')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
            ],
            options={
                'verbose_name': 'خبرة عملية',
                'verbose_name_plural': 'الخبرات العملية',
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100, verbose_name='الدرجة العلمية')),
                ('specialization', models.CharField(max_length=100, verbose_name='التخصص')),
                ('university', models.CharField(max_length=100, verbose_name='الجامعة')),
                ('graduation_year', models.PositiveIntegerField(verbose_name='سنة التخرج')),
            ],
            options={
                'verbose_name': 'مؤهل علمي',
                'verbose_name_plural': 'المؤهلات العلمية',
            },
        ),
    ]
