# Generated by Django 5.2.4 on 2025-09-16 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Teachers', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='teacher_profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='حساب المعلم')),
                ('full_name', models.CharField(max_length=255, verbose_name='الاسم الكامل')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='teachers/profile_pics/', verbose_name='الصورة الشخصية')),
                ('bio', models.TextField(blank=True, verbose_name='نبذة تعريفية')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='teachers/cvs/', verbose_name='ملف السيرة الذاتية')),
            ],
            options={
                'verbose_name': 'ملف معلم',
                'verbose_name_plural': 'ملفات المعلمين',
            },
        ),
        migrations.AddField(
            model_name='qualification',
            name='teacher_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='Teachers.teacherprofile', verbose_name='ملف المعلم'),
        ),
        migrations.AddField(
            model_name='experience',
            name='teacher_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='Teachers.teacherprofile', verbose_name='ملف المعلم'),
        ),
    ]
