# Generated by Django 5.2.4 on 2025-09-21 19:40

import Teachers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to=Teachers.models.teacher_cv_path, verbose_name='ملف السيرة الذاتية'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='full_name',
            field=models.CharField(max_length=60, verbose_name='الاسم الكامل'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=Teachers.models.teacher_profile_pic_path, verbose_name='الصورة الشخصية'),
        ),
    ]
