# Generated by Django 5.2.4 on 2025-09-23 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0003_alter_teacherprofile_cv_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='graduation_year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2025)], verbose_name='سنة التخرج'),
        ),
    ]
