# Generated by Django 5.2.4 on 2025-12-20 00:33

import Teachers.models
import django.core.validators
import user.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0004_alter_qualification_graduation_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to=Teachers.models.teacher_cv_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc'], message='امتداد ملف السيرة الذاتية غير مدعوم. يجب أن يكون الملف من نوع .pdf'), user.validators.validate_file_size], verbose_name='ملف السيرة الذاتية'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=Teachers.models.teacher_profile_pic_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'], message='امتداد الصورة غير مدعوم. الامتدادات المسموح بها هي: .png, .jpg, .jpeg'), user.validators.validate_file_size], verbose_name='الصورة الشخصية'),
        ),
    ]
