# Generated by Django 5.2.4 on 2025-09-16 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقديم')),
                ('status', models.CharField(choices=[('PENDING', 'قيد المراجعة'), ('REVIEWED', 'تمت المراجعة'), ('ACCEPTED', 'مقبول'), ('REJECTED', 'مرفوض')], default='PENDING', max_length=10, verbose_name='حالة الطلب')),
            ],
            options={
                'verbose_name': 'طلب تقديم',
                'verbose_name_plural': 'طلبات التقديم',
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الوظيفة')),
                ('description', models.TextField(verbose_name='وصف الوظيفة')),
                ('required_specialization', models.CharField(max_length=100, verbose_name='التخصص المطلوب')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النشر')),
            ],
            options={
                'verbose_name': 'إعلان وظيفة',
                'verbose_name_plural': 'إعلانات الوظائف',
                'ordering': ['-posted_at'],
            },
        ),
    ]
