# Generated by Django 5.2.4 on 2025-09-16 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Schools', '0001_initial'),
        ('Teachers', '0002_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='school_profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='حساب المدرسة')),
                ('school_name', models.CharField(max_length=255, verbose_name='اسم المدرسة')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='schools/logos/', verbose_name='شعار المدرسة')),
                ('school_type', models.CharField(choices=[('PRIVATE', 'أهلية'), ('GOVERNMENT', 'حكومية'), ('INTERNATIONAL', 'دولية')], max_length=20, verbose_name='نوع المدرسة')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='الموقع (المدينة، الحي)')),
            ],
            options={
                'verbose_name': 'ملف مدرسة',
                'verbose_name_plural': 'ملفات المدارس',
            },
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='Teachers.teacherprofile', verbose_name='المعلم'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='Schools.jobposting', verbose_name='الوظيفة'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='Schools.schoolprofile', verbose_name='المدرسة'),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('job', 'teacher')},
        ),
    ]
