# Generated by Django 4.2.23 on 2025-09-18 21:13

import Schools.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=Schools.models.school_logo_path, verbose_name='شعار المدرسة'),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='school_name',
            field=models.CharField(max_length=50, verbose_name='اسم المدرسة'),
        ),
    ]
