# Generated by Django 4.2.23 on 2025-09-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0003_alter_schoolprofile_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط العرض'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط الطول'),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الموقع (المدينة، الحي)'),
        ),
    ]
