# Generated by Django 5.2.4 on 2025-09-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0005_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='schoolprofile',
            name='longitude',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط (مرئي للمعلمين)'),
        ),
    ]
