# Generated by Django 5.2.4 on 2025-12-20 00:33

import Schools.models
import django.core.validators
import user.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0006_remove_schoolprofile_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='experience_years_required',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='سنوات الخبرة المطلوبة'),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=Schools.models.school_logo_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'], message='امتداد الصورة غير مدعوم. الامتدادات المسموح بها هي: .png, .jpg, .jpeg'), user.validators.validate_file_size], verbose_name='شعار المدرسة'),
        ),
    ]
